export default [
  'You have often have influence, though rarely do you have control.',
  'Remember, you always have the ability to not have an opinion.',
  'It takes what it takes.',
  'Hard work pays off.',
  'You get a compass, not a map.',
  'Be in the business of appreciation, not expectation.',
  'Be better than yesterday.',
  'Do what other\'s will not do today, so you can do what they cannot do tomorrow.',
  'Those who have a ‘why’ to live, can bear with almost any ‘how’.”',
  'Every man has two lives, the second starts when he realizes he has just one.',
  'A happy person wants 10,000 things, a sick person wants just one thing.',
  'In matters of style, swim with the current. In matters of principle, stand like a rock.',
  'Relax. Nothing is under control.',
  'Nobody cares about what has happened to you, they care about how you handle it.',
  'Live in the future, then build what is missing.',
  'There’s nothing wrong with fucking things up every single day. But you have to bring some art to it.',
  'Simplicity is about subtracting the obvious and adding the meaningful.',
  'Only those who attempt the absurd will achieve the impossible.',
  'Get in over your head as often and as joyfully as possible.',
  'There is no greatness where there is not simplicity, goodness, and truth.',
  'I\'m more interested in the mortar than the bricks.',
  'Praise means nothing to the dead.',
  'Absorb what is useful, discard what is useless and add what is specifically your own.',
  'Vision without execution is hallucination.',
  'People of accomplishment rarely sat back and let things happen to them. They went out and happened to things.',
  'Life is complicated. It’s filled with nuance. It’s unsatisfying... If I believe in anything, it is doubt. The root cause of all life’s problems is looking for a simple fucking answer.',
  'Busy is a decision.',
  'An expert is a person who has made all the mistakes that can be made in a very narrow field.',
  'One should use common words to say uncommon things',
];
